{% set name = "pyNSID" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8ca4968057dacf98a92deb772f5732d32cf4f62255192960e49a00a5c05aecb8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - pytest-runner
  run:
    - python >=3
    - cytoolz
    - dask-core >=0.10
    - h5py >=2.6.0
    - numpy >=1.10
    - sidpy >=0.0.2
    - six
    - toolz

test:
  imports:
    - pyNSID

about:
  home: https://github.com/pycroscopy/pyNSID
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Framework for storing, visualizing, and processing N-Dimensional Spectroscopic and Imaging Data (NSID)
  doc_url: https://pycroscopy.github.io/pyNSID/
  dev_url: https://github.com/pycroscopy/pyNSID

extra:
  recipe-maintainers:
    - gduscher
    - ssomnath
    - ramav87
